### ISSUE TITLE
Can it build on Ubuntu16.04

### ISSUE THREAD

**Issue by xiazhibin** [BinomialLLC/basis_universal#185]
My working space is Ubuntu16.04.But Ubuntu16.04 doesn't support `GLIBC_2.27`.

Can this project build on Ubuntu16.04.Is there build guide in doc?

My build env is gcc 5.4.0, cmake 3.5.1,but get those error:
```
/Projects/basis_universal/basisu_basis_file.cpp: In member function ‘void basisu::basisu_file::fixup_crcs()’:
/home/bin381/CLionProjects/basis_universal/transcoder/basisu.h:91:41: error: expected primary-expression before ‘,’ token
 #define BASISU_OFFSETOF(s, m) offsetof(s, m)
                                         ^
/Projects/basis_universal/basisu_basis_file.cpp:169:102: note: in expansion of macro ‘BASISU_OFFSETOF’
 t::crc16(&pHeader->m_data_size, sizeof(basist::basis_file_header) - BASISU_OFFS
                                                                     ^
/Projects/basis_universal/basisu_basis_file.cpp:169:145: error: ‘m_data_size’ was not declared in this scope
 st::basis_file_header) - BASISU_OFFSETOF(basist::basis_file_header, m_data_size
                                                                     ^
/Projects/basis_universal/transcoder/basisu.h:91:43: note: in definition of macro ‘BASISU_OFFSETOF’
 #define BASISU_OFFSETOF(s, m) offsetof(s, m)
                                           ^
/Projects/basis_universal/transcoder/basisu.h:91:44: error: ‘offsetof’ was not declared in this scope
 #define BASISU_OFFSETOF(s, m) offsetof(s, m)
                                            ^
/Projects/basis_universal/basisu_basis_file.cpp:169:102: note: in expansion of macro ‘BASISU_OFFSETOF’
 t::crc16(&pHeader->m_data_size, sizeof(basist::basis_file_header) - BASISU_OFFS
```

**Comment by richgel999** [comment]
I'm currently using Ubuntu v18.04. I want it to work on older versions. This problem should be simple to fix.

**Comment by xiazhibin** [comment]
I found that it should be built with gcc7. but doc says that build with gcc5!
